# 345M
Global:
  device: gpu
  seed: 1024
  reader_config: ./gpt_reader.yaml
  cloze_eval: False # True for LAMBADA Dataset; False for WikiText

# 100000 72000
# 500000 360000

Data:
  batch_size:
    global_batch_size: 1 
    local_batch_size: 1
    micro_batch_size: 1



Model:
  vocab_size: 50304
  hidden_size: 1024
  num_layers: 24
  num_attention_heads: 16
  ffn_hidden_size: 4096
  hidden_dropout_prob: 0.0 #0.1
  attention_probs_dropout_prob: 0.0 #0.1
  max_position_embeddings: 1024
  type_vocab_size: 16
  initializer_range: 0.02
  use_recompute: True
  recompute_granularity:
  fused_linear: True
  
Engine:
  mix_precision:
    use_pure_fp16: True

Distributed:
  dp_degree: 1
  mp_degree: 1
  pp_degree: 1
  sharding:
    sharding_degree: 1
    sharding_stage: 1
    sharding_offload: False

Optimizer:
  name: FusedAdamW
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  epsilon: 1.0e-8
  lr:
    name: CosineAnnealingWithWarmupDecay
    decay_steps: 360000
    warmup_rate: 0.01
    max_lr: 5.0e-5
    min_lr: 1.0e-5
  grad_clip:
    name: "ClipGradByGlobalNorm"
    clip_norm: 1.0
  tensor_fusion: False




Eval:
  eval_path: /workspace/distill-gpt/PaddleFleetX/lambada_test.jsonl #./wikitext-103/wiki.valid.tokens #
  cloze_eval: True
  overlapping_eval: 32
  batch_size: 1 
  max_seq_len: 1024
  logging_freq: 10
  
Quantization:
  enable: True
  weight_quantize_type: 'abs_max'
  activation_quantize_type: 'moving_average_abs_max'
  activation_preprocess_type: 'PACT'
  weight_bits: 8
  activation_bits: 8
  quantizable_layer_type: ['Conv2D', 'Linear', 'Conv2DTranspose', 'ColumnParallelLinear', 'RowParallelLinear']
  onnx_format: True

PTQ:
  quantizable_op_type: ["mul", "matmul", "matmul_v2"]
  weight_quantize_type: 'abs_max'
  activation_quantize_type: 'moving_average_abs_max'
  is_full_quantize: False
  batch_size: 1 
  batch_nums: 1 
